/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myterminal1_xili_myterminal1_Driver_Key */

#ifndef _Included_com_myterminal1_xili_myterminal1_Driver_Key
#define _Included_com_myterminal1_xili_myterminal1_Driver_Key
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myterminal1_xili_myterminal1_Driver_Key
 * Method:    readKey0Status
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_myterminal1_xili_myterminal1_Driver_Key_readKey0Status
  (JNIEnv *, jclass);

/*
 * Class:     com_myterminal1_xili_myterminal1_Driver_Key
 * Method:    readKey1Status
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_myterminal1_xili_myterminal1_Driver_Key_readKey1Status
  (JNIEnv *, jclass);

/*
 * Class:     com_myterminal1_xili_myterminal1_Driver_Key
 * Method:    readKey2Status
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_myterminal1_xili_myterminal1_Driver_Key_readKey2Status
  (JNIEnv *, jclass);

/*
 * Class:     com_myterminal1_xili_myterminal1_Driver_Key
 * Method:    readKey3Status
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_myterminal1_xili_myterminal1_Driver_Key_readKey3Status
  (JNIEnv *, jclass);

/*
 * Class:     com_myterminal1_xili_myterminal1_Driver_Key
 * Method:    setKey0Status
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_myterminal1_xili_myterminal1_Driver_Key_setKey0Status
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_myterminal1_xili_myterminal1_Driver_Key
 * Method:    setKey1Status
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_myterminal1_xili_myterminal1_Driver_Key_setKey1Status
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_myterminal1_xili_myterminal1_Driver_Key
 * Method:    setKey2Status
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_myterminal1_xili_myterminal1_Driver_Key_setKey2Status
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_myterminal1_xili_myterminal1_Driver_Key
 * Method:    setKey3Status
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_myterminal1_xili_myterminal1_Driver_Key_setKey3Status
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
